### ISSUE TITLE
_Prefix/NullabilityCompat.h file is missing so compile fails

### ISSUE THREAD

**Issue by CreativityKills** [hbang/headers#4]
> Making all for tweak Hooker…
    ==> Preprocessing Tweak.xm…
    ==> Compiling Tweak.xm (armv7)…
    In file included from <built-in>:184:
    In file included from <command line>:5:
    /opt/kirb/theos/Prefix.pch:6:10: fatal error: '_Prefix/NullabilityCompat.h' file not found
        #import <_Prefix/NullabilityCompat.h>
                ^
    1 error generated.
    make[3]: *** [.theos/obj/debug/armv7/Tweak.xm.a3e1ec91.o] Error 1
    make[2]: *** [.theos/obj/debug/armv7/Hooker.dylib] Error 2
    make[1]: *** [internal-library-all_] Error 2
    make: *** [Hooker.all.tweak.variables] Error 2`

**Comment by kirb** [comment]
Fixed in 99ea1c8, sorry :(
